name: daily-worker
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"
jobs:
  update-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Update Tasks
        run: |
          curl --request POST \
          --url 'https://notion.rocke.dev/api/workers/update-tasks' \
          --header "Content-Type: application/json" \
          --data '{"databaseId":"${{ secrets.DATABASE_ID }}"}' \
          --fail-with-body
