name: daily-worker
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"
jobs:
  update-tasks:
    runs-on: ubuntu-latest
    env:
      PROJECT_DATABASE: "${{ secrets.DATABASE_ID }}"
      NOTION_TOKEN: "${{ secrets.NOTION_TOKEN }}"
      CLIENT_TZ: America/Chicago
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Update Tasks
        run: node index.mjs
